version: "3.8"
services:
  caddy:
    image: caddy
    networks:
      - dingusnet
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "caddy_data:/data/"
      - "caddy_config:/config/"
      - "./Caddyfile:/etc/caddy/Caddyfile:ro"

volumes:
  caddy_data:
  caddy_config:

networks:
  dingusnet:
    external: true
